Fix user flairs and new comment indicators lost in rebase
lo-cafe/winston pull request #243
Opened 2023-11-13 19:53 UTC by zanderb98

Fix flairs and new comment indicators that were lost in rebase. Streamable videos are still bonked but too lazy to fix now

2023-11-17 21:10 UTC, Kinark requested changes

2023-11-17 21:10 UTC, Kinark commented on winston/components/Badge.swift
>                  .fill(commentTheme?.unseenDot.cs(cs).color() ?? .red)
There's now a component for that glowing dot (that's also used on PostLinks), please replace this ZStack for the component and use .equatable()

2023-11-17 21:10 UTC, Kinark commented on winston/components/Badge.swift
> +
Please make this an Equatable component

2023-11-18 21:43 UTC, zanderb98 commented on winston/components/Badge.swift
> +
Done

2023-11-18 21:43 UTC, zanderb98 commented on winston/components/Badge.swift
>                  .fill(commentTheme?.unseenDot.cs(cs).color() ?? .red)
Done!

2023-11-19 00:44 UTC, Kinark requested changes

2023-11-19 00:44 UTC, Kinark commented on winston/components/Badge.swift
> +          }
We **cannot** pass the post down to the child views, not even inside wrappers, don't do that, please. Besides, creating a PostWrapper to be passed as an environmentObject every time badge is invoked is a terrible idea. Optional observable objects are bad, we don't try to workaround that.

2023-11-19 01:20 UTC, zanderb98 commented on winston/components/Badge.swift
> +          }
Sounds good. Reverted those changes for now. We can figure that out in a futurePR

2023-11-20 01:25 UTC, Kinark approved these changes

2023-11-20 01:25 UTC, merged